### ISSUE TITLE
Week 11 Project Review

### ISSUE THREAD

**Issue by AlreadyAsleep** [jessecdaniels/heartstart#1]
Below is a review of your project that will outline how it stacks up against the requirements and what opportunities I see.
Here is a link to the requirements for reference: https://docs.google.com/document/d/1OHe_R4irOpoKX3QGD3HZWCgNLaHScVuviWGa95Be830/edit#

## Mandatory Requirements
- 3 CSS Styles: I saw many different CSS classes in multiple different files. Great work
- Responsive: Site responds well and looks good on mobile
- Javascript: Saw the form validation. Although I didn't get the alert when I missed the math question
- Comments: Saw a reasonable use of comments
- 5 commits: You have 21. Great work
- README: looks good. Add a little more background to bring it home
## Feature Requirements
Based on our conversations and what I can see in your site I would attempt the following features from the requirements list:
- Flexbox and Grid✔️ 
- Form Validation ✔️ 
- Media Queres ✔️ 

Looks good! Fix that JS issue I mentioned and you are golden. It has been a pleasure having you in class!

**Comment by jessecdaniels** [comment]
Thanks so much for all you help! I completed the readme and fixed the form validation. Thanks so much for all your help, it was greatly appreciated!
